# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Backend in Python

on: [push, pull_request]

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Type Check
      run: |
        mypy api_bookmarks
    - name: Format Check
      run: |
        black --check api_bookmarks
    - name: Lint
      run: |
        pylint api_bookmarks
    - name: Unit Test
      run: |
        python -m pytest --cov=api_bookmarks --cov-report=xml api_bookmarks 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
